name: PR Labels

on:
  pull_request:
    branches:
      - main

jobs:
  label:
    name: Require SemVer Label (major, minor, patch)
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1.1.2
        with:
          mode: minimum
          count: 1
          labels: "major, minor, patch"
