name: Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  label:
    name: Require PR Label major/minor/patch
    # only run if the PR is not a draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1.1.2
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
