name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      PIXLET_BINARY_PATH: ./functions/axilla/pixlet/
      PIXLET_BINARY: pixlet-github
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
