name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    env:
      PIXLET_BINARY: pixlet-github
      PIXLET_BINARY_PATH: ./functions/axilla/pixlet/
    steps:
      - uses: actions/checkout@v2
      - name: Install libwebp-dev
        run: sudo apt-get install -y libwebp-dev
      - name: Working directory check
        run: pwd
      - name: chmod pixlet binary
        run: sudo chmod +x "$PIXLET_BINARY_PATH$PIXLET_BINARY"
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:ci
