name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
